services:
    EzSystems\EzPlatformAutomatedTranslationBundle\Controller\TranslationController:
        decorates: EzSystems\EzPlatformAdminUiBundle\Controller\TranslationController
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']